# Filtering and Ordering

In [2]:
import pandas as pd

In [12]:
df = pd.read_csv(r"H:\Phyton Tutorial\Web Scrapping\Web Scrapping Project 1\Companies_Project1.csv")
df

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,"611,289",6.7%,"2,100,000","Bentonville, Arkansas"
1,2,Amazon,Retail and cloud computing,"513,983",9.4%,"1,540,000","Seattle, Washington"
2,3,Exxon Mobil,Petroleum industry,"413,680",44.8%,"62,000","Spring, Texas"
3,4,Apple,Electronics industry,"394,328",7.8%,"164,000","Cupertino, California"
4,5,UnitedHealth Group,Healthcare,"324,162",12.7%,"400,000","Minnetonka, Minnesota"
5,6,CVS Health,Healthcare,"322,467",10.4%,"259,500","Woonsocket, Rhode Island"
6,7,Berkshire Hathaway,Conglomerate,"302,089",9.4%,"383,000","Omaha, Nebraska"
7,8,Alphabet,Technology,"282,836",9.8%,"156,000","Mountain View, California"
8,9,McKesson Corporation,Health,"276,711",4.8%,"48,500","Irving, Texas"
9,10,Chevron Corporation,Petroleum industry,"246,252",51.6%,"43,846","San Ramon, California"
10,11,AmerisourceBergen,Pharmaceutical industry,"238,587",11.5%,"41,500","Chesterbrook, Pennsylvania"
11,12,Costco,Retail,"226,954",15.8%,"304,000","Issaquah, Washington"
12,13,Microsoft,Technology,"198,270",18.0%,"221,000","Redmond, Washington"
13,14,Cardinal Health,Healthcare,"181,364",11.6%,"46,035","Dublin, Ohio"
14,15,Cigna,Health Insurance,"180,516",3.7%,"70,231","Bloomfield, Connecticut"
15,16,Marathon Petroleum,Petroleum industry,"180,012",27.6%,"17,800","Findlay, Ohio"
16,17,Phillips 66,Petroleum industry,"175,702",53.0%,"13,000","Houston, Texas"
17,18,Valero Energy,Petroleum industry,"171,189",58.0%,"9,743","San Antonio, Texas"
18,19,Ford Motor Company,Automotive industry,"158,057",15.9%,"173,000","Dearborn, Michigan"
19,20,The Home Depot,Retail,"157,403",4.1%,"471,600","Atlanta, Georgia"
20,21,General Motors,Automotive,"156,735",23.4%,"167,000","Detroit, Michigan"
21,22,Elevance Health,Healthcare,"156,595",13.0%,"102,200","Indianapolis, Indiana"
22,23,JPMorgan Chase,Financial services,"154,792",21.7%,"293,723","New York City, New York"
23,24,Kroger,Retail,"148,258",7.5%,"430,000","Cincinnati, Ohio"
24,25,Centene,Healthcare,"144,547",14.7%,"74,300","St. Louis, Missouri"
25,26,Verizon Communications,Telecommunications,"136,835",2.4%,"117,100","New York City, New York"
26,27,Walgreens Boots Alliance,Pharmaceutical industry,"132,703",10.7%,"262,500","Deerfield, Illinois"
27,28,Fannie Mae,Financials,"121,596",19.7%,"8,000","Washington, D.C."
28,29,Comcast,Telecommunications,"121,427",4.3%,"186,000","Philadelphia, Pennsylvania"
29,30,AT&T,Conglomerate,"120,741",28.5%,"160,700","Dallas, Texas"
30,31,Meta Platforms,Technology,"116,609",1.1%,"86,482","Menlo Park, California"
31,32,Bank of America,Financials,"115,053",22.6%,"216,823","Charlotte, North Carolina"
32,33,Target Corporation,Retail,"109,120",2.9%,"440,000","Minneapolis, Minnesota"
33,34,Dell Technologies,Technology,"102,301",4.4%,"133,000","Round Rock, Texas"
34,35,Archer Daniels Midland,Food industry,"101,556",19.1%,"41,181","Chicago, Illinois"
35,36,Citigroup,Financials,"101,078",26.6%,"238,104","New York City, New York"
36,37,United Parcel Service,Transportation,"100,338",3.1%,"404,700","Atlanta, Georgia"
37,38,Pfizer,Pharmaceutical industry,"100,330",23.4%,"83,000","New York City, New York"
38,39,Lowe's,Retail,"97,059",0.8%,"244,500","Mooresville, North Carolina"
39,40,Johnson & Johnson,Pharmaceutical industry,"94,943",1.2%,"152,700","New Brunswick, New Jersey"
40,41,FedEx,Transportation,"93,512",11.4%,"518,249","Memphis, Tennessee"
41,42,Humana,Health Insurance,"92,870",11.8%,"67,100","Louisville, Kentucky"
42,43,Energy Transfer Partners,Petroleum industry,"89,876",33.3%,"12,565","Dallas, Texas"
43,44,State Farm,Financials,"89,328",8.6%,"60,519","Bloomington, Illinois"
44,45,Freddie Mac,Financials,"86,717",31.6%,"7,819","McLean, Virginia"
45,46,PepsiCo,Beverage,"86,859",8.7%,"315,000","Purchase, New York"
46,47,Wells Fargo,Financials,"82,859",0.5%,"238,000","San Francisco, California"
47,48,The Walt Disney Company,Media,"82,722",22.7%,"195,800","Burbank, California"
48,49,ConocoPhillips,Petroleum industry,"82,156",69.9%,"9,500","Houston, Texas"
49,50,Tesla,Automotive and Energy,"81,462",51.4%,"127,855","Austin, Texas"
50,51,Procter & Gamble,Consumer products Manufacturing,"80,187",5.3%,"106,000","Cincinnati, Ohio"
51,52,United States Postal Service,Logistics,"78,620",2.0%,"576,000","Washington, D.C."
52,53,Albertsons,Retail,"77,650",8.0%,"198,650","Boise, Idaho"
53,54,General Electric,Conglomerate,"76,555",3.2%,"172,000","Boston, Massachusetts"
54,55,MetLife,Financials,"69,898",1.7%,"45,000","New York City, New York"
55,56,Goldman Sachs,Financials,"68,711",5.7%,"48,500","New York City, New York"
56,57,Sysco,Food Service,"68,636",33.8%,"70,510","Houston, Texas"
57,58,Bunge Limited,Food industry,"67,232",13.7%,"23,000","White Plains, New York"
58,59,RTX Corporation,Conglomerate,"67,074",4.2%,"182,000","Arlington County, Virginia"
59,60,Boeing,Aerospace and defense,"66,608",6.9%,"156,000","Chicago, Illinois"
60,61,StoneX Group,Financials,"66,036",55.3%,305,"New York City, New York"
61,62,Lockheed Martin,Aerospace and Defense,"65,984",1.6%,"116,000","Bethesda, Maryland"
62,63,Morgan Stanley,Financials,"65,936",7.9%,"82,427","New York City, New York"
63,64,Intel,Technology,"63,054",20.1%,"131,900","Santa Clara, California"
64,65,HP,Technology,"62,983",0.8%,"58,000","Palo Alto, California"
65,66,TD Synnex,Infotech,"62,344",97.2%,"28,500","Clearwater, Florida"
66,67,IBM,Technology,"60,530",16.3%,"303,100","Armonk, New York"
67,68,HCA Healthcare,Healthcare,"60,233",2.5%,"250,500","Nashville, Tennessee"
68,69,Prudential Financial,Financials,"60,050",15.3%,"39,583","Newark, New Jersey"
69,70,Caterpillar,Machinery,"59,427",16.6%,"109,100","Deerfield, Illinois"
70,71,Merck & Co.,Pharmaceutical industry,"59,283",15.8%,"68,000","Kenilworth, New Jersey"
71,72,World Fuel Services,Petroleum industry and Logistics,"59,043",88.4%,"5,214","Miami, Florida"
72,73,New York Life Insurance Company,Insurance,"58,445",14.2%,"15,050","New York City, New York"
73,74,Enterprise Products,Petroleum industry,"58,186",42.6%,"7,300","Houston, Texas"
74,75,AbbVie,Pharmaceutical industry,"58,054",3.3%,"50,000","Lake Bluff, Illinois"
75,76,Plains All American Pipeline,Petroleum industry,"57,342",36.3%,"4,100","Houston, Texas"
76,77,Dow Chemical Company,Chemical industry,"56,902",3.5%,"37,800","Midland, Michigan"
77,78,AIG,Insurance,"56,437",8.4%,"26,200","New York City, New York"
78,79,American Express,Financial,"55,625",27.3%,"77,300","New York City, New York"
79,80,Publix,Retail,"54,942",13.5%,"242,000","Lakeland, Florida"
80,81,Charter Communications,Telecommunications,"54,022",4.5%,"101,700","Stamford, Connecticut"
81,82,Tyson Foods,Food Processing,"53,282",13.2%,"142,000","Springdale, Arkansas"
82,83,John Deere,Agriculture manufacturing,"52,577",19.4%,"82,239","Moline, Illinois"
83,84,Cisco,Telecom Hardware Manufacturing,"51,557",3.5%,"83,300","San Jose, California"
84,85,Nationwide Mutual Insurance Company,Financial,"51,450",8.6%,"24,791","Columbus, Ohio"
85,86,Allstate,Insurance,"51,412",3.4%,"54,250","Northfield Township, Cook County, Illinois"
86,87,Delta Air Lines,Airline,"50,582",69.2%,"95,000","Atlanta, Georgia"
87,88,Liberty Mutual,Insurance,"49,956",3.6%,"50,000","Boston, Massachusetts"
88,89,TJX,Retail,"49,936",2.9%,"329,000","Framingham, Massachusetts"
89,90,Progressive Corporation,Insurance,"49,611",4.0%,"55,063","Mayfield Village, Ohio"
90,91,American Airlines,Airline,"48,971",63.9%,"129,700","Fort Worth, Texas"
91,92,CHS,Agriculture cooperative,"47,194",24.3%,"10,014","Inver Grove Heights, Minnesota"
92,93,Performance Food Group,Food Processing,"47,194",61.6%,"34,825","Richmond, Virginia"
93,94,PBF Energy,Petroleum industry,"46,830",71.8%,"3,616","Parsippany–Troy Hills, New Jersey"
94,95,Nike,Apparel,"46,710",4.9%,"79,100","Beaverton, Oregon"
95,96,Best Buy,Retail,"46,298",10.6%,"71,100","Richfield, Minnesota"
96,97,Bristol-Myers Squibb,Pharmaceutical industry,"46,159",0.5%,"34,300","New York City, New York"
97,98,United Airlines,Airline,"44,955",82.5%,"92,795","Chicago, Illinois"
98,99,Thermo Fisher Scientific,Laboratory instruments,"44,915",14.5%,"130,000","Waltham, Massachusetts"
99,100,Qualcomm,Technology,"44,200",31.7%,"51,000","San Diego, California"

In [11]:
pd.set_option('display.max.rows', 101)

In [6]:
df[df['Rank'] <= 10]

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,"611,289",6.7%,"2,100,000","Bentonville, Arkansas"
1,2,Amazon,Retail and cloud computing,"513,983",9.4%,"1,540,000","Seattle, Washington"
2,3,Exxon Mobil,Petroleum industry,"413,680",44.8%,"62,000","Spring, Texas"
3,4,Apple,Electronics industry,"394,328",7.8%,"164,000","Cupertino, California"
4,5,UnitedHealth Group,Healthcare,"324,162",12.7%,"400,000","Minnetonka, Minnesota"
5,6,CVS Health,Healthcare,"322,467",10.4%,"259,500","Woonsocket, Rhode Island"
6,7,Berkshire Hathaway,Conglomerate,"302,089",9.4%,"383,000","Omaha, Nebraska"
7,8,Alphabet,Technology,"282,836",9.8%,"156,000","Mountain View, California"
8,9,McKesson Corporation,Health,"276,711",4.8%,"48,500","Irving, Texas"
9,10,Chevron Corporation,Petroleum industry,"246,252",51.6%,"43,846","San Ramon, California"

In [8]:
specific_industries = ['Healthcare','Technology']

df[df['Industry'].isin(specific_industries)]

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
4,5,UnitedHealth Group,Healthcare,"324,162",12.7%,"400,000","Minnetonka, Minnesota"
5,6,CVS Health,Healthcare,"322,467",10.4%,"259,500","Woonsocket, Rhode Island"
7,8,Alphabet,Technology,"282,836",9.8%,"156,000","Mountain View, California"
12,13,Microsoft,Technology,"198,270",18.0%,"221,000","Redmond, Washington"
13,14,Cardinal Health,Healthcare,"181,364",11.6%,"46,035","Dublin, Ohio"
21,22,Elevance Health,Healthcare,"156,595",13.0%,"102,200","Indianapolis, Indiana"
24,25,Centene,Healthcare,"144,547",14.7%,"74,300","St. Louis, Missouri"
30,31,Meta Platforms,Technology,"116,609",1.1%,"86,482","Menlo Park, California"
33,34,Dell Technologies,Technology,"102,301",4.4%,"133,000","Round Rock, Texas"
63,64,Intel,Technology,"63,054",20.1%,"131,900","Santa Clara, California"
64,65,HP,Technology,"62,983",0.8%,"58,000","Palo Alto, California"
66,67,IBM,Technology,"60,530",16.3%,"303,100","Armonk, New York"
67,68,HCA Healthcare,Healthcare,"60,233",2.5%,"250,500","Nashville, Tennessee"
99,100,Qualcomm,Technology,"44,200",31.7%,"51,000","San Diego, California"

In [15]:
df[df['Industry'].str.contains('Technology')]

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
7,8,Alphabet,Technology,"282,836",9.8%,"156,000","Mountain View, California"
12,13,Microsoft,Technology,"198,270",18.0%,"221,000","Redmond, Washington"
30,31,Meta Platforms,Technology,"116,609",1.1%,"86,482","Menlo Park, California"
33,34,Dell Technologies,Technology,"102,301",4.4%,"133,000","Round Rock, Texas"
63,64,Intel,Technology,"63,054",20.1%,"131,900","Santa Clara, California"
64,65,HP,Technology,"62,983",0.8%,"58,000","Palo Alto, California"
66,67,IBM,Technology,"60,530",16.3%,"303,100","Armonk, New York"
99,100,Qualcomm,Technology,"44,200",31.7%,"51,000","San Diego, California"

In [20]:
df2 = df.set_index('Industry')
df2

,Rank,Name,Revenue (USD millions),Revenue growth,Employees,Headquarters
Industry,,,,,,
Retail,1,Walmart,"611,289",6.7%,"2,100,000","Bentonville, Arkansas"
Retail and cloud computing,2,Amazon,"513,983",9.4%,"1,540,000","Seattle, Washington"
Petroleum industry,3,Exxon Mobil,"413,680",44.8%,"62,000","Spring, Texas"
Electronics industry,4,Apple,"394,328",7.8%,"164,000","Cupertino, California"
Healthcare,5,UnitedHealth Group,"324,162",12.7%,"400,000","Minnetonka, Minnesota"
Healthcare,6,CVS Health,"322,467",10.4%,"259,500","Woonsocket, Rhode Island"
Conglomerate,7,Berkshire Hathaway,"302,089",9.4%,"383,000","Omaha, Nebraska"
Technology,8,Alphabet,"282,836",9.8%,"156,000","Mountain View, California"
Health,9,McKesson Corporation,"276,711",4.8%,"48,500","Irving, Texas"
Petroleum industry,10,Chevron Corporation,"246,252",51.6%,"43,846","San Ramon, California"
Pharmaceutical industry,11,AmerisourceBergen,"238,587",11.5%,"41,500","Chesterbrook, Pennsylvania"
Retail,12,Costco,"226,954",15.8%,"304,000","Issaquah, Washington"
Technology,13,Microsoft,"198,270",18.0%,"221,000","Redmond, Washington"
Healthcare,14,Cardinal Health,"181,364",11.6%,"46,035","Dublin, Ohio"
Health Insurance,15,Cigna,"180,516",3.7%,"70,231","Bloomfield, Connecticut"
Petroleum industry,16,Marathon Petroleum,"180,012",27.6%,"17,800","Findlay, Ohio"
Petroleum industry,17,Phillips 66,"175,702",53.0%,"13,000","Houston, Texas"
Petroleum industry,18,Valero Energy,"171,189",58.0%,"9,743","San Antonio, Texas"
Automotive industry,19,Ford Motor Company,"158,057",15.9%,"173,000","Dearborn, Michigan"
Retail,20,The Home Depot,"157,403",4.1%,"471,600","Atlanta, Georgia"
Automotive,21,General Motors,"156,735",23.4%,"167,000","Detroit, Michigan"
Healthcare,22,Elevance Health,"156,595",13.0%,"102,200","Indianapolis, Indiana"
Financial services,23,JPMorgan Chase,"154,792",21.7%,"293,723","New York City, New York"
Retail,24,Kroger,"148,258",7.5%,"430,000","Cincinnati, Ohio"
Healthcare,25,Centene,"144,547",14.7%,"74,300","St. Louis, Missouri"
Telecommunications,26,Verizon Communications,"136,835",2.4%,"117,100","New York City, New York"
Pharmaceutical industry,27,Walgreens Boots Alliance,"132,703",10.7%,"262,500","Deerfield, Illinois"
Financials,28,Fannie Mae,"121,596",19.7%,"8,000","Washington, D.C."
Telecommunications,29,Comcast,"121,427",4.3%,"186,000","Philadelphia, Pennsylvania"
Conglomerate,30,AT&T,"120,741",28.5%,"160,700","Dallas, Texas"
Technology,31,Meta Platforms,"116,609",1.1%,"86,482","Menlo Park, California"
Financials,32,Bank of America,"115,053",22.6%,"216,823","Charlotte, North Carolina"
Retail,33,Target Corporation,"109,120",2.9%,"440,000","Minneapolis, Minnesota"
Technology,34,Dell Technologies,"102,301",4.4%,"133,000","Round Rock, Texas"
Food industry,35,Archer Daniels Midland,"101,556",19.1%,"41,181","Chicago, Illinois"
Financials,36,Citigroup,"101,078",26.6%,"238,104","New York City, New York"
Transportation,37,United Parcel Service,"100,338",3.1%,"404,700","Atlanta, Georgia"
Pharmaceutical industry,38,Pfizer,"100,330",23.4%,"83,000","New York City, New York"
Retail,39,Lowe's,"97,059",0.8%,"244,500","Mooresville, North Carolina"
Pharmaceutical industry,40,Johnson & Johnson,"94,943",1.2%,"152,700","New Brunswick, New Jersey"
Transportation,41,FedEx,"93,512",11.4%,"518,249","Memphis, Tennessee"
Health Insurance,42,Humana,"92,870",11.8%,"67,100","Louisville, Kentucky"
Petroleum industry,43,Energy Transfer Partners,"89,876",33.3%,"12,565","Dallas, Texas"
Financials,44,State Farm,"89,328",8.6%,"60,519","Bloomington, Illinois"
Financials,45,Freddie Mac,"86,717",31.6%,"7,819","McLean, Virginia"
Beverage,46,PepsiCo,"86,859",8.7%,"315,000","Purchase, New York"
Financials,47,Wells Fargo,"82,859",0.5%,"238,000","San Francisco, California"
Media,48,The Walt Disney Company,"82,722",22.7%,"195,800","Burbank, California"
Petroleum industry,49,ConocoPhillips,"82,156",69.9%,"9,500","Houston, Texas"
Automotive and Energy,50,Tesla,"81,462",51.4%,"127,855","Austin, Texas"
Consumer products Manufacturing,51,Procter & Gamble,"80,187",5.3%,"106,000","Cincinnati, Ohio"
Logistics,52,United States Postal Service,"78,620",2.0%,"576,000","Washington, D.C."
Retail,53,Albertsons,"77,650",8.0%,"198,650","Boise, Idaho"
Conglomerate,54,General Electric,"76,555",3.2%,"172,000","Boston, Massachusetts"
Financials,55,MetLife,"69,898",1.7%,"45,000","New York City, New York"
Financials,56,Goldman Sachs,"68,711",5.7%,"48,500","New York City, New York"
Food Service,57,Sysco,"68,636",33.8%,"70,510","Houston, Texas"
Food industry,58,Bunge Limited,"67,232",13.7%,"23,000","White Plains, New York"
Conglomerate,59,RTX Corporation,"67,074",4.2%,"182,000","Arlington County, Virginia"
Aerospace and defense,60,Boeing,"66,608",6.9%,"156,000","Chicago, Illinois"
Financials,61,StoneX Group,"66,036",55.3%,305,"New York City, New York"
Aerospace and Defense,62,Lockheed Martin,"65,984",1.6%,"116,000","Bethesda, Maryland"
Financials,63,Morgan Stanley,"65,936",7.9%,"82,427","New York City, New York"
Technology,64,Intel,"63,054",20.1%,"131,900","Santa Clara, California"
Technology,65,HP,"62,983",0.8%,"58,000","Palo Alto, California"
Infotech,66,TD Synnex,"62,344",97.2%,"28,500","Clearwater, Florida"
Technology,67,IBM,"60,530",16.3%,"303,100","Armonk, New York"
Healthcare,68,HCA Healthcare,"60,233",2.5%,"250,500","Nashville, Tennessee"
Financials,69,Prudential Financial,"60,050",15.3%,"39,583","Newark, New Jersey"
Machinery,70,Caterpillar,"59,427",16.6%,"109,100","Deerfield, Illinois"
Pharmaceutical industry,71,Merck & Co.,"59,283",15.8%,"68,000","Kenilworth, New Jersey"
Petroleum industry and Logistics,72,World Fuel Services,"59,043",88.4%,"5,214","Miami, Florida"
Insurance,73,New York Life Insurance Company,"58,445",14.2%,"15,050","New York City, New York"
Petroleum industry,74,Enterprise Products,"58,186",42.6%,"7,300","Houston, Texas"
Pharmaceutical industry,75,AbbVie,"58,054",3.3%,"50,000","Lake Bluff, Illinois"
Petroleum industry,76,Plains All American Pipeline,"57,342",36.3%,"4,100","Houston, Texas"
Chemical industry,77,Dow Chemical Company,"56,902",3.5%,"37,800","Midland, Michigan"
Insurance,78,AIG,"56,437",8.4%,"26,200","New York City, New York"
Financial,79,American Express,"55,625",27.3%,"77,300","New York City, New York"
Retail,80,Publix,"54,942",13.5%,"242,000","Lakeland, Florida"
Telecommunications,81,Charter Communications,"54,022",4.5%,"101,700","Stamford, Connecticut"
Food Processing,82,Tyson Foods,"53,282",13.2%,"142,000","Springdale, Arkansas"
Agriculture manufacturing,83,John Deere,"52,577",19.4%,"82,239","Moline, Illinois"
Telecom Hardware Manufacturing,84,Cisco,"51,557",3.5%,"83,300","San Jose, California"
Financial,85,Nationwide Mutual Insurance Company,"51,450",8.6%,"24,791","Columbus, Ohio"
Insurance,86,Allstate,"51,412",3.4%,"54,250","Northfield Township, Cook County, Illinois"
Airline,87,Delta Air Lines,"50,582",69.2%,"95,000","Atlanta, Georgia"
Insurance,88,Liberty Mutual,"49,956",3.6%,"50,000","Boston, Massachusetts"
Retail,89,TJX,"49,936",2.9%,"329,000","Framingham, Massachusetts"
Insurance,90,Progressive Corporation,"49,611",4.0%,"55,063","Mayfield Village, Ohio"
Airline,91,American Airlines,"48,971",63.9%,"129,700","Fort Worth, Texas"
Agriculture cooperative,92,CHS,"47,194",24.3%,"10,014","Inver Grove Heights, Minnesota"
Food Processing,93,Performance Food Group,"47,194",61.6%,"34,825","Richmond, Virginia"
Petroleum industry,94,PBF Energy,"46,830",71.8%,"3,616","Parsippany–Troy Hills, New Jersey"
Apparel,95,Nike,"46,710",4.9%,"79,100","Beaverton, Oregon"
Retail,96,Best Buy,"46,298",10.6%,"71,100","Richfield, Minnesota"
Pharmaceutical industry,97,Bristol-Myers Squibb,"46,159",0.5%,"34,300","New York City, New York"
Airline,98,United Airlines,"44,955",82.5%,"92,795","Chicago, Illinois"
Laboratory instruments,99,Thermo Fisher Scientific,"44,915",14.5%,"130,000","Waltham, Massachusetts"
Technology,100,Qualcomm,"44,200",31.7%,"51,000","San Diego, California"

In [22]:
df2.filter(items = ['Rank', 'Headquarters'])

,Rank,Headquarters
Industry,,
Retail,1,"Bentonville, Arkansas"
Retail and cloud computing,2,"Seattle, Washington"
Petroleum industry,3,"Spring, Texas"
Electronics industry,4,"Cupertino, California"
Healthcare,5,"Minnetonka, Minnesota"
Healthcare,6,"Woonsocket, Rhode Island"
Conglomerate,7,"Omaha, Nebraska"
Technology,8,"Mountain View, California"
Health,9,"Irving, Texas"
Petroleum industry,10,"San Ramon, California"
Pharmaceutical industry,11,"Chesterbrook, Pennsylvania"
Retail,12,"Issaquah, Washington"
Technology,13,"Redmond, Washington"
Healthcare,14,"Dublin, Ohio"
Health Insurance,15,"Bloomfield, Connecticut"
Petroleum industry,16,"Findlay, Ohio"
Petroleum industry,17,"Houston, Texas"
Petroleum industry,18,"San Antonio, Texas"
Automotive industry,19,"Dearborn, Michigan"
Retail,20,"Atlanta, Georgia"
Automotive,21,"Detroit, Michigan"
Healthcare,22,"Indianapolis, Indiana"
Financial services,23,"New York City, New York"
Retail,24,"Cincinnati, Ohio"
Healthcare,25,"St. Louis, Missouri"
Telecommunications,26,"New York City, New York"
Pharmaceutical industry,27,"Deerfield, Illinois"
Financials,28,"Washington, D.C."
Telecommunications,29,"Philadelphia, Pennsylvania"
Conglomerate,30,"Dallas, Texas"
Technology,31,"Menlo Park, California"
Financials,32,"Charlotte, North Carolina"
Retail,33,"Minneapolis, Minnesota"
Technology,34,"Round Rock, Texas"
Food industry,35,"Chicago, Illinois"
Financials,36,"New York City, New York"
Transportation,37,"Atlanta, Georgia"
Pharmaceutical industry,38,"New York City, New York"
Retail,39,"Mooresville, North Carolina"
Pharmaceutical industry,40,"New Brunswick, New Jersey"
Transportation,41,"Memphis, Tennessee"
Health Insurance,42,"Louisville, Kentucky"
Petroleum industry,43,"Dallas, Texas"
Financials,44,"Bloomington, Illinois"
Financials,45,"McLean, Virginia"
Beverage,46,"Purchase, New York"
Financials,47,"San Francisco, California"
Media,48,"Burbank, California"
Petroleum industry,49,"Houston, Texas"
Automotive and Energy,50,"Austin, Texas"
Consumer products Manufacturing,51,"Cincinnati, Ohio"
Logistics,52,"Washington, D.C."
Retail,53,"Boise, Idaho"
Conglomerate,54,"Boston, Massachusetts"
Financials,55,"New York City, New York"
Financials,56,"New York City, New York"
Food Service,57,"Houston, Texas"
Food industry,58,"White Plains, New York"
Conglomerate,59,"Arlington County, Virginia"
Aerospace and defense,60,"Chicago, Illinois"
Financials,61,"New York City, New York"
Aerospace and Defense,62,"Bethesda, Maryland"
Financials,63,"New York City, New York"
Technology,64,"Santa Clara, California"
Technology,65,"Palo Alto, California"
Infotech,66,"Clearwater, Florida"
Technology,67,"Armonk, New York"
Healthcare,68,"Nashville, Tennessee"
Financials,69,"Newark, New Jersey"
Machinery,70,"Deerfield, Illinois"
Pharmaceutical industry,71,"Kenilworth, New Jersey"
Petroleum industry and Logistics,72,"Miami, Florida"
Insurance,73,"New York City, New York"
Petroleum industry,74,"Houston, Texas"
Pharmaceutical industry,75,"Lake Bluff, Illinois"
Petroleum industry,76,"Houston, Texas"
Chemical industry,77,"Midland, Michigan"
Insurance,78,"New York City, New York"
Financial,79,"New York City, New York"
Retail,80,"Lakeland, Florida"
Telecommunications,81,"Stamford, Connecticut"
Food Processing,82,"Springdale, Arkansas"
Agriculture manufacturing,83,"Moline, Illinois"
Telecom Hardware Manufacturing,84,"San Jose, California"
Financial,85,"Columbus, Ohio"
Insurance,86,"Northfield Township, Cook County, Illinois"
Airline,87,"Atlanta, Georgia"
Insurance,88,"Boston, Massachusetts"
Retail,89,"Framingham, Massachusetts"
Insurance,90,"Mayfield Village, Ohio"
Airline,91,"Fort Worth, Texas"
Agriculture cooperative,92,"Inver Grove Heights, Minnesota"
Food Processing,93,"Richmond, Virginia"
Petroleum industry,94,"Parsippany–Troy Hills, New Jersey"
Apparel,95,"Beaverton, Oregon"
Retail,96,"Richfield, Minnesota"
Pharmaceutical industry,97,"New York City, New York"
Airline,98,"Chicago, Illinois"
Laboratory instruments,99,"Waltham, Massachusetts"
Technology,100,"San Diego, California"

In [30]:
df2.filter(like = 'Health', axis = 0)
#items buat index
#like buat 1 value
#axis 1, nggak muncul, axis 0 muncul

,Rank,Name,Revenue (USD millions),Revenue growth,Employees,Headquarters
Industry,,,,,,
Healthcare,5,UnitedHealth Group,"324,162",12.7%,"400,000","Minnetonka, Minnesota"
Healthcare,6,CVS Health,"322,467",10.4%,"259,500","Woonsocket, Rhode Island"
Health,9,McKesson Corporation,"276,711",4.8%,"48,500","Irving, Texas"
Healthcare,14,Cardinal Health,"181,364",11.6%,"46,035","Dublin, Ohio"
Health Insurance,15,Cigna,"180,516",3.7%,"70,231","Bloomfield, Connecticut"
Healthcare,22,Elevance Health,"156,595",13.0%,"102,200","Indianapolis, Indiana"
Healthcare,25,Centene,"144,547",14.7%,"74,300","St. Louis, Missouri"
Health Insurance,42,Humana,"92,870",11.8%,"67,100","Louisville, Kentucky"
Healthcare,68,HCA Healthcare,"60,233",2.5%,"250,500","Nashville, Tennessee"

In [36]:
df2.iloc[22]

Rank                                           23
Name                               JPMorgan Chase
Revenue (USD millions)                    154,792
Revenue growth                              21.7%
Employees                                 293,723
Headquarters              New York City, New York
Name: Financial services, dtype: object

# Order by

In [43]:
df[df['Rank'] <= 10 ].sort_values(by = 'Revenue growth', ascending = True)

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
5,6,CVS Health,Healthcare,"322,467",10.4%,"259,500","Woonsocket, Rhode Island"
4,5,UnitedHealth Group,Healthcare,"324,162",12.7%,"400,000","Minnetonka, Minnesota"
8,9,McKesson Corporation,Health,"276,711",4.8%,"48,500","Irving, Texas"
2,3,Exxon Mobil,Petroleum industry,"413,680",44.8%,"62,000","Spring, Texas"
9,10,Chevron Corporation,Petroleum industry,"246,252",51.6%,"43,846","San Ramon, California"
0,1,Walmart,Retail,"611,289",6.7%,"2,100,000","Bentonville, Arkansas"
3,4,Apple,Electronics industry,"394,328",7.8%,"164,000","Cupertino, California"
1,2,Amazon,Retail and cloud computing,"513,983",9.4%,"1,540,000","Seattle, Washington"
6,7,Berkshire Hathaway,Conglomerate,"302,089",9.4%,"383,000","Omaha, Nebraska"
7,8,Alphabet,Technology,"282,836",9.8%,"156,000","Mountain View, California"